import {setupInputMode,bindHeldButton} from './input-mode.mjs';
import {Game,STAGES} from './core.mjs';
import {GOSPEL,OPENING} from './gospel.mjs';
import {GROUND_Y,bodyScale,locomotionTime} from './visuals.mjs';
const $=id=>document.getElementById(id), canvas=$('game'),ctx=canvas.getContext('2d'),game=new Game();
const images={},actors={},input={},texts=[];let openingSeen=false,reflectionShown=false;let gospelOpen=false;let loaded=false,selected=0,last=performance.now(),previous='menu',muted=true,audio,arrowHover=false;
const device=setupInputMode(clearInput);
let progress={unlocked:0,stars:{}};try{const saved=JSON.parse(localStorage.getItem('daud-goliat-v1'));if(saved&&Number.isInteger(saved.unlocked))progress={unlocked:Math.max(0,Math.min(4,saved.unlocked)),stars:saved.stars||{}};}catch{}selected=progress.unlocked;
const loadImage=src=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error(`Gagal memuat ${src}`));im.src=src;});
async function load(){const tasks=[];for(const name of ['daud','domba','serigala','singa','beruang','goliat'])tasks.push((async()=>{const base=`assets/generated/sprites/${name}/`;const [sheet,res]=await Promise.all([loadImage(base+'sprite-sheet-alpha.png?v=locomotion8'),fetch(base+'manifest.json?v=locomotion8')]);if(!res.ok)throw new Error('Metadata karakter tidak tersedia');actors[name]={sheet,meta:await res.json()};})());
 for(const group of ['backgrounds','items','effects'])for(const name of group==='backgrounds'?['padang','perbukitan','lembah_goliat']:group==='items'?['shield','arrow','kasut']:['stone','shield_dome','hit_spark','threat_arrow'])tasks.push(loadImage(`assets/generated/${group}/${name}.png`).then(im=>images[name]=im));
 await Promise.all(tasks);loaded=true;$('start').disabled=false;$('start').textContent='Mulai perjalanan  →';$('loading').textContent='Lima domba adalah nyawamu. Jaga mereka tetap bersama.';stageButtons();}
function stageButtons(){const holder=$('stage-select');if(!holder)return;holder.innerHTML='';STAGES.forEach((s,i)=>{const b=document.createElement('button');b.textContent=i+1;b.disabled=i>progress.unlocked;b.className=i===selected?'selected':'';b.title=`${s.name}${i>progress.unlocked?' — selesaikan stage sebelumnya':''}`;b.setAttribute('aria-label',b.title);b.onclick=()=>{selected=i;stageButtons();$('stage-name').textContent=s.name;};holder.append(b);});$('stage-name').textContent=STAGES[selected].name;}
function start(stage=selected){selected=stage;reflectionShown=false;game.start(stage);texts.length=0;previous='playing';$('overlay').classList.add('hidden');$('hud').classList.remove('hidden');$('stage-name').textContent=STAGES[stage].name;$('chapter').textContent=`BAB ${String(stage+1).padStart(2,'0')}`;canvas.focus();if(!openingSeen){game.state='message';previous='message';showGospel(stage,'opening',()=>{openingSeen=true;game.state='playing';previous='playing';$('overlay').classList.add('hidden');canvas.focus();});}}
$('start').onclick=()=>start();
function panel(html){$('overlay').classList.remove('gospel-view');$('panel').innerHTML=html;$('overlay').classList.remove('hidden');}
function showGospel(stage,position,done){
 const opening=position==='opening';const message=opening?OPENING:GOSPEL[stage];if(!message){done();return;}
 clearInput();gospelOpen=true;$('help').disabled=true;$('pause').disabled=true;
 panel(`<article class="gospel-message" aria-labelledby="gospel-title"><span class="eyebrow">${opening?'SEBELUM PERJALANAN DIMULAI':`RENUNGAN STAGE ${stage+1}`}</span><h2 id="gospel-title">${message.title}</h2>${message.body.split('\n\n').filter(Boolean).map(paragraph=>`<p>${paragraph}</p>`).join('')}<blockquote>${opening?message.verse:`“${message.verse}”`}<cite>— ${message.reference}</cite></blockquote><button id="gospel-continue" class="primary">${opening?'Mulai perjalanan →':'Lihat hasil →'}</button></article>`);
 $('overlay').classList.add('gospel-view');$('overlay').scrollTop=0;
 $('gospel-continue').onclick=()=>{gospelOpen=false;$('help').disabled=false;$('pause').disabled=false;$('overlay').classList.remove('gospel-view');clearInput();done();};
 $('gospel-continue').focus({preventScroll:true});
}
function pause(){if(gospelOpen||game.state==='celebrating')return;game.pause();clearInput();if(game.state==='paused')panel(`<span class="eyebrow">TARIK NAPAS SEJENAK</span><h2>Kawanan menunggumu.</h2><p>Waktu, musuh, dan durasi item berhenti selama jeda.</p><button class="primary" id="resume">Lanjutkan →</button><button class="secondary" id="retry">Ulangi stage</button><p style="margin-top:18px">A/D gerak · J pukul · K tendang · tahan/lepas L tongkat kuat<br>Tahan/lepas Space untuk umban · 1/2/3 untuk item</p>`);else $('overlay').classList.add('hidden');bindPanel();}
function bindPanel(){if($('resume'))$('resume').onclick=()=>{if(game.state==='paused')game.pause();$('overlay').classList.add('hidden');canvas.focus();};if($('retry'))$('retry').onclick=()=>{if(game.state==='paused'){panel('<span class="eyebrow">ULANGI PERCOBAAN?</span><h2>Mulai lagi dari awal stage.</h2><p>Progres gelombang saat ini akan hilang.</p><button id="confirm-retry" class="primary">Ya, ulangi</button><button id="resume" class="secondary">Kembali bermain</button>');$('confirm-retry').onclick=()=>start(game.stage);bindPanel();}else start(game.stage);};if($('next'))$('next').onclick=()=>start(Math.min(4,game.stage+1));}
$('pause').onclick=pause;$('mobile-help').onclick=()=>$('help').onclick();
$('help').onclick=()=>{if(gospelOpen||game.state==='celebrating')return;if(game.state==='playing'){game.pause();clearInput();}panel(`<div class="help-copy"><span class="eyebrow">CARA BERMAIN</span><h2>Kamu menjaga lima nyawa.</h2><p><b>A/D atau ←/→</b> bergerak. <b>J</b> pukul cepat, <b>K</b> tendang untuk mendorong, <b>Tahan lalu lepas L</b> untuk tongkat: 25–60 damage, penuh dalam 1 detik.</p><p><b>Tahan Space</b> sampai bar penuh, lalu lepaskan untuk batu kuat. Mulai dengan 5 batu; setiap tembakan memakai 1. Ambil batu (+1) yang muncul acak setiap 5 detik. Serang dahi Goliat ketika tanda emas muncul.</p><p><b>1 Shield:</b> domba kebal 15 detik. <b>2 Panah:</b> musuh sekitar langsung kalah; Goliat menerima 90 damage. <b>3 Kasut:</b> lebih cepat 8 detik.</p><p>Ambil item dengan berjalan mendekatinya. Domba yang hilang tidak kembali sampai stage berikutnya. <b>Esc</b> menjeda permainan.</p><button id="close-help" class="primary">Mengerti →</button></div>`);$('close-help').onclick=()=>{if(game.state==='paused'){game.pause();$('overlay').classList.add('hidden');canvas.focus();}else if(game.state==='menu')location.reload();else{previous='';}};};
function clearInput(){game.player.staffCharge=null;for(const k of Object.keys(input))input[k]=false;if(game.player.charge!==null){game.player.charge=null;game.animate(game.player,'idle');}}
const keys=new Set(['KeyA','KeyD','ArrowLeft','ArrowRight','KeyJ','KeyK','KeyL','Space','Digit1','Digit2','Digit3','Escape']);
window.addEventListener('keydown',e=>{if(!keys.has(e.code)||e.target instanceof HTMLInputElement)return;if(e.code==='Space'&&e.target instanceof HTMLButtonElement)return;device.keyboard();if(device.blocked)return;e.preventDefault();if(e.code==='KeyA'||e.code==='ArrowLeft')input.left=true;if(e.code==='KeyD'||e.code==='ArrowRight')input.right=true;if(e.repeat)return;
 if(e.code==='Escape'){if(game.state==='playing'||game.state==='paused')pause();return;}
 if(e.code==='Space')game.chargeStart();if(e.code==='KeyJ')game.attack('punch');if(e.code==='KeyK')game.attack('kick');if(e.code==='KeyL')game.staffStart();if(e.code.startsWith('Digit'))game.item(Number(e.code.at(-1))-1);
});
window.addEventListener('keyup',e=>{if(e.code==='KeyL'){e.preventDefault();game.staffRelease();}if(e.code==='KeyA'||e.code==='ArrowLeft')input.left=false;if(e.code==='KeyD'||e.code==='ArrowRight')input.right=false;if(e.code==='Space'){e.preventDefault();game.release();}});
window.addEventListener('blur',()=>{if(game.state==='playing')pause();clearInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.state==='playing')pause();});
document.querySelectorAll('[data-item]').forEach(b=>{b.onclick=()=>{game.item(Number(b.dataset.item));canvas.focus();};if(b.dataset.item==='1'){b.onmouseenter=()=>arrowHover=true;b.onmouseleave=()=>arrowHover=false;b.onfocus=()=>arrowHover=true;b.onblur=()=>arrowHover=false;}});
document.querySelectorAll('[data-hold]').forEach(b=>bindHeldButton(b,{
 press:()=>{device.touch();if(device.blocked)return;if(b.dataset.hold==='sling')game.chargeStart();else if(b.dataset.hold==='staff')game.staffStart();else input[b.dataset.hold]=true;},
 release:()=>{if(b.dataset.hold==='sling')game.release();else if(b.dataset.hold==='staff')game.staffRelease();else input[b.dataset.hold]=false;},
 cancel:()=>{if(b.dataset.hold==='sling')game.player.charge=null;else if(b.dataset.hold==='staff')game.player.staffCharge=null;else input[b.dataset.hold]=false;}
}));document.querySelectorAll('[data-action]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();device.touch();if(!device.blocked)game.attack(b.dataset.action);};});
$('sound').onclick=()=>{muted=!muted;$('sound').textContent=`Suara: ${muted?'mati':'aktif'}`;if(!muted){audio||=new(window.AudioContext||window.webkitAudioContext)();audio.resume();tone(440,.1);}};
function tone(freq,duration=.06){if(muted||!audio)return;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='triangle';osc.frequency.setValueAtTime(freq,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(freq*.55,audio.currentTime+duration);gain.gain.setValueAtTime(.08,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration);}
function sprite(name,state,x,y,scale=1,face=1,time=0,alpha=1){const a=actors[name];if(!a)return;let row=a.meta.animation.rows[state];if(!row){state=name==='singa'&&state==='defeat'?'hurt':'idle';row=a.meta.animation.rows[state];}const frames=a.meta.frame_layout.rows[state];const index=row.loop?Math.floor(time*(row.fps||8))%frames.length:Math.min(frames.length-1,Math.floor(time*(row.fps||8)));const r=frames[index];ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);scale*=bodyScale(name,state);ctx.scale(face*scale,scale);ctx.drawImage(a.sheet,r.x,r.y,r.w,r.h,-r.w/2,-r.h+24,r.w,r.h);ctx.restore();}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function label(text,x,y,size=14,color='#fff9e6'){ctx.font=`600 ${size}px Arial`;ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,x,y);}
function render(){ctx.clearRect(0,0,1280,720);ctx.save();if(game.state==='celebrating'){const t=game.cinematic.elapsed;const smooth=v=>{v=Math.max(0,Math.min(1,v));return v*v*(3-2*v);};const zoom=1+.65*smooth(t/1.2);const pan=smooth((t-1.5)/2);const focus=game.cinematic.enemyX*(1-pan)+game.player.x*pan;const cx=Math.max(640/zoom,Math.min(1280-640/zoom,focus));const cy=Math.max(360/zoom,Math.min(720-360/zoom,GROUND_Y[STAGES[game.stage].bg]-100));ctx.translate(640,360);ctx.scale(zoom,zoom);ctx.translate(-cx,-cy);}const stage=STAGES[game.state==='menu'?selected:game.stage];if(images[stage.bg])ctx.drawImage(images[stage.bg],0,stage.bg==='padang'?0:15,1280,720);else{ctx.fillStyle='#ded0a9';ctx.fillRect(0,0,1280,720);}const ground=GROUND_Y[stage.bg];
 const menu=game.state==='menu';const flockX=menu?930:640;
 for(let i=0;i<game.sheep;i++){const x=flockX+(i-2)*37,y=ground-(i%2)*3;ellipse(x,y,25,5,'#483d2733');sprite('domba',game.shield>0?'idle':game.flockImmune>0?'panic':'idle',x,y,.34,i%2?1:-1,game.time+i*.28,game.flockImmune>0&&Math.sin(game.time*25)>0?.6:1);}
 if(game.shield>0&&images.shield_dome){ctx.globalAlpha=game.shield<3?.55+.3*Math.sin(game.time*12):.75;ctx.drawImage(images.shield_dome,flockX-150,ground-140,300,153);ctx.globalAlpha=1;}
 if(arrowHover&&!menu){ellipse(game.player.x,ground,280,25,'#e9c37935');ctx.strokeStyle='#b9853c';ctx.setLineDash([5,6]);ctx.beginPath();ctx.ellipse(game.player.x,ground,280,25,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}
 for(const item of game.pickups){const key=item.item==='stone'?'stone':['shield','arrow','kasut'][item.item];const y=ground-46+Math.sin(game.time*4)*5;ellipse(item.x,ground,23,6,'#5d45252b');ctx.drawImage(images[key],item.x-23,y-32,46,46);label(item.item==='stone'?'+1 BATU':String(item.item+1),item.x,y-38,13,'#456153');}
 for(const e of game.enemies){const scale=e.type==='goliat'?.91:e.type==='beruang'?.68:e.type==='singa'?.6:.49;ellipse(e.x,ground,e.type==='goliat'?45:36,8,'#483d272b');sprite(e.type,e.anim,e.x,ground,scale,e.face,e.type==='goliat'&&e.anim==='walk'?locomotionTime('goliat',e.strideDistance,actors.goliat.meta.animation.rows.walk):e.animTime,e.dead?Math.min(1,e.timer*2):1);
  if(!e.dead){const y=ground-(e.type==='goliat'?310:e.type==='beruang'?165:135);if(e.type!=='goliat'&&e.hp<e.max){ctx.fillStyle='#423c3655';ctx.fillRect(e.x-24,y,48,4);ctx.fillStyle='#8b4a38';ctx.fillRect(e.x-24,y,48*e.hp/e.max,4);}
   if(e.mode==='wind'){label(e.target==='flock'?'! DOMBA':e.target==='throw'?'BATU ↓':'!',e.x,y-13,18,'#922e1d');ctx.fillStyle='#9b422b';ctx.fillRect(e.x-23,y-6,46*(1-e.timer/e.wind),3);if(e.target==='throw'){ellipse(640,ground,105,13,`rgba(177,62,31,${.25+.15*Math.sin(game.time*14)})`);}}
   if(e.weak){ellipse(e.x+e.face*18,ground-240,12,12,'#f4d58399');label('DAHI TERBUKA',e.x,y-12,13,'#705619');}
  }
 }
 const p=game.player;const px=menu?790:p.x;ellipse(px,ground,31,7,'#483d273b');sprite('daud',menu?'idle':p.anim,px,ground,.57,menu?1:p.face,menu?performance.now()/1000:p.anim==='run'?locomotionTime('daud',p.strideDistance,actors.daud.meta.animation.rows.run):p.animTime,p.immune>0&&Math.sin(game.time*30)>0?.4:1);
 if((p.charge!==null||p.staffCharge!==null)&&!menu){const charge=p.staffCharge!==null?p.staffCharge:(p.charge||0)/.8;ctx.strokeStyle=charge>=1?'#ffe1a3':'#fff8dc';ctx.lineWidth=3;ctx.beginPath();ctx.arc(px,ground-100,25,-Math.PI/2,-Math.PI/2+Math.PI*2*Math.min(1,charge));ctx.stroke();}
 for(const s of game.shots){const target=game.enemies.find(e=>e.type==='goliat'&&e.weak&&!e.dead);const y=target&&s.full?ground-235:ground-77;ctx.drawImage(images.stone,s.x-9,y-7,s.full?22:16,s.full?18:13);}
 for(const f of game.effects){if(f.kind==='hit'){ctx.globalAlpha=f.t/.3;ctx.drawImage(images.hit_spark,f.x-35,ground-115,70,65);ctx.globalAlpha=1;}if(f.kind==='arrows'){ctx.strokeStyle='#714b2a';ctx.lineWidth=3;for(let i=0;i<13;i++){const x=f.x-250+i*40,y=ground-(f.t*500+i%3*40);ctx.beginPath();ctx.moveTo(x-10,y-50);ctx.lineTo(x,y);ctx.stroke();}}}
 for(const t of texts){ctx.globalAlpha=Math.max(0,t.t);label(t.text,t.x,ground-110-(1-t.t)*45,19,'#fff7d5');ctx.globalAlpha=1;}
 if(game.queue.length&&game.spawnIn<=1&&game.breakTime<=0){const left=game.side()<0;ctx.save();ctx.translate(left?36:1244,ground-105);ctx.scale(left?1:-1,1);ctx.drawImage(images.threat_arrow,-18,-25,36,50);ctx.restore();}
 if(game.breakTime>0){label(game.wave===0?'BERSIAP MENJAGA KAWANAN':'GELOMBANG BERIKUTNYA',640,245,14,'#4c5c40');label(String(Math.ceil(game.breakTime)),640,289,35,'#344d3b');}
 ctx.restore();if(game.state==='celebrating'){ctx.fillStyle='#17241ee6';ctx.fillRect(0,0,1280,42);ctx.fillRect(0,658,1280,62);label('KAWANAN SELAMAT',640,688,17,'#f4dbaa');}
}
let sheepLast=-1;
function ui(){const celebrating=game.state==='celebrating';document.querySelector('.arena').classList.toggle('touch-playing',game.state==='playing');document.querySelector('.arena').classList.toggle('cinematic',celebrating);$('help').disabled=gospelOpen||celebrating;if(game.sheep!==sheepLast){$('sheep-icons').innerHTML=Array.from({length:5},(_,i)=>`<img class="${i>=game.sheep?'lost':''}" src="assets/generated/bases/domba.png" alt="${i<game.sheep?'Domba aman':'Domba hilang'}">`).join('');$('sheep-icons').setAttribute('aria-label',`${game.sheep} domba tersisa`);$('sheep-count').textContent=`${game.sheep} / 5 domba aman`;sheepLast=game.sheep;}
 $('wave-label').textContent=`GELOMBANG ${game.wave+1} / ${STAGES[game.stage].waves.length}`;$('enemy-count').textContent=`${game.queue.length+game.enemies.filter(e=>!e.dead).length} musuh tersisa`;
 for(let i=0;i<3;i++){$(`stock-${i}`).textContent=game.inventory[i];const b=document.querySelector(`[data-item="${i}"]`);b.disabled=game.state!=='playing'||game.inventory[i]===0||game.itemCooldown>0||(i===0&&game.shield>0)||(i===2&&game.speed>0);}
 const staffCharging=game.player.staffCharge!=null;const power=staffCharging?game.player.staffCharge:(game.player.charge||0)/.8;$('weapon-label').textContent=staffCharging?'TONGKAT':'UMBAN';$('ammo-count').textContent=`Batu: ${game.ammo}`;$('charge-fill').style.width=`${Math.min(1,power)*100}%`;$('charge-label').textContent=staffCharging?(power>=1?'60 damage — lepas L!':'Tahan L untuk memperkuat'):game.ammo===0?'Batu habis — ambil di tanah':power>=1?'Penuh — lepaskan!':'Tahan lalu lepas Space';$('toast').classList.toggle('hidden',!(game.noticeTime>0)||game.state!=='playing');$('toast').textContent=game.notice;$('buffs').textContent=[game.shield>0?`SHIELD ${Math.ceil(game.shield)} dtk`:'',game.speed>0?`KASUT ${Math.ceil(game.speed)} dtk`:''].filter(Boolean).join('  ·  ');
 const boss=game.enemies.find(e=>e.type==='goliat'&&!e.dead);$('boss').classList.toggle('hidden',!boss);if(boss){$('boss-fill').style.width=`${boss.hp/9}%`;$('boss-state').textContent=boss.weak?'Dahi terbuka':`Fase ${boss.phase} · ${Math.ceil(boss.hp)} / 900`;}
 if(game.state!==previous){previous=game.state;if(game.state==='won'||game.state==='lost'){clearInput();const won=game.state==='won';let saved=true;const stars=game.sheep===5?3:game.sheep>=3?2:1;if(won){progress.unlocked=Math.min(4,Math.max(progress.unlocked,game.stage+1));progress.stars[game.stage]=Math.max(progress.stars[game.stage]||0,stars);try{localStorage.setItem('daud-goliat-v1',JSON.stringify(progress));}catch{saved=false;}}
 const showResult=()=>{panel(`<span class="eyebrow">${won?'KAWANAN SELAMAT':'PERJALANAN BELUM BERAKHIR'}</span><h2>${won?(game.stage===4?'Keberanian mengalahkan raksasa.':'Kamu menjaga mereka.'):'Coba sekali lagi, Daud.'}</h2>${won?`<div class="result-stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div>`:''}<p>${won?`${game.sheep} domba selamat`:'Kelima domba telah lari'} · ${game.kills} musuh dikalahkan<br>${Math.floor(game.time/60)} menit ${Math.floor(game.time%60)} detik${saved?'':'<br>Progres tidak dapat disimpan di browser ini.'}</p>${won&&game.stage<4?'<button id="next" class="primary">Stage berikutnya →</button>':''}<button id="retry" class="${won&&game.stage<4?'secondary':'primary'}">Mainkan lagi</button>`);bindPanel();};if(won&&!reflectionShown){reflectionShown=true;showGospel(game.stage,'akhir',showResult);}else showResult();}
 }
}
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;if(loaded){const wasPlaying=game.state==='playing';if(!document.hidden&&!device.blocked)game.update(dt,input);if(wasPlaying){for(const e of game.events){if(e.type==='hit'){texts.push({x:e.x,text:e.value,t:1});tone(170);}else if(e.type==='pickup'||e.type==='item')tone(650,.15);else if(e.type==='sheep')tone(100,.3);else if(e.type==='sling')tone(400);}for(const t of texts)t.t-=dt;while(texts.length&&texts[0].t<=0)texts.shift();}render();ui();}requestAnimationFrame(frame);}
load().catch(error=>{$('loading').textContent='Chargement gagal. Jalankan game lewat server lokal (lihat README). '+error.message;$('loading').classList.add('error');});requestAnimationFrame(frame);
